spring:
  datasource:
    url: jdbc:postgresql://expensively-roused-flathead.data-1.usw2.tembo.io:5432/postgres_test
    username: ${TEST_DB_USERNAME}
    password: ${TEST_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/test_migration
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: validate
    open-in-view: false
  jta:
    enabled: true
