package auth.service.app.model.enums;

public class AuditEnums {
  public enum AuditPlatform {
    PLATFORM_CREATE,
    PLATFORM_UPDATE,
    PLATFORM_DELETE_SOFT,
    PLATFORM_DELETE_HARD,
    PLATFORM_RESTORE
  }

  public enum AuditPermission {
    PERMISSION_CREATE,
    PERMISSION_UPDATE,
    PERMISSION_DELETE_SOFT,
    PERMISSION_DELETE_HARD,
    PERMISSION_RESTORE
  }

  public enum AuditRole {
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE_SOFT,
    ROLE_DELETE_HARD,
    ROLE_RESTORE,
    ASSIGN_PLATFORM_PERMISSION,
    UNASSIGN_PLATFORM_PERMISSION
  }

  public enum AuditProfile {
    PROFILE_CREATE,
    PROFILE_UPDATE,
    PROFILE_EMAIL_UPDATE,
    PROFILE_PASSWORD_UPDATE,
    PROFILE_ADDRESS_CREATE,
    PROFILE_ADDRESS_UPDATE,
    PROFILE_ADDRESS_DELETE,
    PROFILE_DELETE_SOFT,
    PROFILE_DELETE_HARD,
    PROFILE_RESTORE,
    PROFILE_LOGIN,
    PROFILE_LOGIN_ERROR,
    PROFILE_LOGOUT,
    PROFILE_LOGOUT_ERROR,
    PROFILE_VALIDATE_INIT,
    PROFILE_VALIDATE_EXIT,
    PROFILE_VALIDATE_ERROR,
    PROFILE_RESET_INIT,
    PROFILE_RESET_EXIT,
    PROFILE_RESET_ERROR,
    TOKEN_REFRESH,
    TOKEN_REFRESH_ERROR,
    ASSIGN_PLATFORM_ROLE,
    UNASSIGN_PLATFORM_ROLE
  }
}
