package auth.service.app.model.enums;

public class AuditEnums {
  public enum AuditPlatform {
    PLATFORM_CREATE,
    PLATFORM_UPDATE,
    PLATFORM_DELETE_SOFT,
    PLATFORM_DELETE_HARD,
    PLATFORM_RESTORE
  }

  public enum AuditPermission {
    PERMISSION_CREATE,
    PERMISSION_UPDATE,
    PERMISSION_DELETE_SOFT,
    PERMISSION_DELETE_HARD,
    PERMISSION_RESTORE
  }

  public enum AuditRole {
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE_SOFT,
    ROLE_DELETE_HARD,
    ROLE_RESTORE,
    ASSIGN_PLATFORM_PERMISSION,
    UNASSIGN_PLATFORM_PERMISSION
  }

  public enum AuditProfile {
    PROFILE_CREATE,
    PROFILE_UPDATE,
    PROFILE_EMAIL_UPDATE,
    PROFILE_PASSWORD_UPDATE,
    PROFILE_ADDRESS_CREATE,
    PROFILE_ADDRESS_UPDATE,
    PROFILE_ADDRESS_DELETE,
    PROFILE_DELETE_SOFT,
    PROFILE_DELETE_HARD,
    PROFILE_RESTORE,
    PROFILE_LOGIN,
    PROFILE_LOGIN_ERROR,
    PROFILE_LOGOUT,
    PROFILE_LOGOUT_ERROR,
    PROFILE_VALIDATE_INIT,
    PROFILE_VALIDATE_EXIT,
    PROFILE_VALIDATE_ERROR,
    PROFILE_RESET_INIT,
    PROFILE_RESET_EXIT,
    PROFILE_RESET_ERROR,
    TOKEN_REFRESH,
    TOKEN_REFRESH_ERROR,
    ASSIGN_PLATFORM_ROLE,
    UNASSIGN_PLATFORM_ROLE
  }

  public enum AuditUsers {
    CREATE_USER,
    UPDATE_USER,
    UPDATE_USER_EMAIL,
    UPDATE_USER_PASSWORD,
    UPDATE_USER_DELETE_ADDRESS,
    SOFT_DELETE_USER,
    HARD_DELETE_USER,
    RESTORE_USER,
    ASSIGN_ROLE,
    UNASSIGN_ROLE,
    ASSIGN_APP,
    UNASSIGN_APP,
    USER_LOGIN,
    USER_LOGIN_ERROR,
    USER_LOGOUT,
    USER_LOGOUT_ERROR,
    USER_VALIDATE_INIT,
    USER_VALIDATE_EXIT,
    USER_VALIDATE_ERROR,
    USER_RESET_INIT,
    USER_RESET_EXIT,
    USER_RESET,
    USER_RESET_ERROR,
    TOKEN_REFRESH,
    TOKEN_REFRESH_ERROR
  }

  public enum AuditRoles {
    CREATE_ROLE,
    UPDATE_ROLE,
    SOFT_DELETE_ROLE,
    HARD_DELETE_ROLE,
    RESTORE_ROLE,
    ASSIGN_PERMISSION,
    UNASSIGN_PERMISSION
  }

  public enum AuditPermissions {
    CREATE_PERMISSION,
    UPDATE_PERMISSION,
    SOFT_DELETE_PERMISSION,
    HARD_DELETE_PERMISSION,
    RESTORE_PERMISSION
  }

  public enum AuditApps {
    CREATE_APP,
    UPDATE_APP,
    SOFT_DELETE_APP,
    HARD_DELETE_APP,
    RESTORE_APP
  }
}
