name: Flyway Migrate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Database Connection
        if: github.event_name == 'push'
        run: |
          pg_isready -h ${{ secrets.DB_HOST_PROD }} -p 5432 -U ${{ secrets.DB_USERNAME }} -d ${{ secrets.DB_DBNAME }}

      - name: Test Database Connection
        if: github.event_name == 'pull_request'
        run: |
          pg_isready -h ${{ secrets.DB_HOST_SANDBOX }} -p 5432 -U ${{ secrets.DB_USERNAME }} -d ${{ secrets.DB_DBNAME }}

      - name: Install Flyway
        run: |
          sudo apt-get update && sudo apt-get install -y curl tar
          curl -L https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/10.19.0/flyway-commandline-10.19.0-linux-x64.tar.gz | tar xvz
          sudo mv flyway-10.19.0/flyway /usr/local/bin/flyway
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Run Flyway Migrations
        if: github.event_name == 'push'
        run: |
          flyway -url=jdbc:postgresql://${{ secrets.DB_HOST_PROD }}:5432/${{ secrets.DB_DBNAME }} \
                 -user=${{ secrets.DB_USERNAME }} \
                 -password=${{ secrets.DB_PASSWORD }} \
                 -locations=filesystem:app/src/main/resources/db/migration \
                 migrate

      - name: Run Flyway Migrations
        if: github.event_name == 'pull_request'
        run: |
          flyway -url=jdbc:postgresql://${{ secrets.DB_HOST_DEV }}:5432/${{ secrets.DB_DB }} \
                 -user=${{ secrets.DB_USERNAME }} \
                 -password=${{ secrets.DB_PASSWORD }} \
                 -locations=filesystem:app/src/main/resources/db/migration \
                 migrate
