name: Flyway Validate

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment Name to Validate (options: PROD, SANDBOX)"
        required: true
        default: "SANDBOX"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Input
        run: |
          if [[ "${{ inputs.environment }}" != "PROD" && "${{ inputs.environment }}" != "SANDBOX" ]]; then
            echo "Error: Invalid environment '${{ inputs.environment }}'. Allowed values are PROD or SANDBOX."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Database Connection
        if: ${{ inputs.environment == 'PROD' || inputs.environment == 'SANDBOX' }}
        run: |
          if [[ "${{ inputs.environment }}" == "PROD" ]]; then
            psql postgresql://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST_PROD }}:5432/${{ secrets.DB_DBNAME }} -c '\l';
          else
            psql postgresql://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST_SANDBOX }}:5432/${{ secrets.DB_DBNAME }} -c '\l';
          fi

      - name: Install Flyway
        run: |
          curl -L https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/10.19.0/flyway-commandline-10.19.0-linux-x64.tar.gz | tar xvz
          sudo mv flyway-10.19.0 /usr/local/flyway
          echo "/usr/local/flyway" >> $GITHUB_PATH

      - name: Run Flyway Validation
        if: ${{ inputs.environment == 'PROD' || inputs.environment == 'SANDBOX' }}
        run: |
          if [[ "${{ inputs.environment }}" == "PROD" ]]; then
            flyway -url=jdbc:postgresql://${{ secrets.DB_HOST_PROD }}:5432/${{ secrets.DB_DBNAME }} \
                   -user=${{ secrets.DB_USERNAME }} \
                   -password=${{ secrets.DB_PASSWORD }} \
                   -locations=filesystem:app/src/main/resources/db/migration \
                   validate;
          else
            flyway -url=jdbc:postgresql://${{ secrets.DB_HOST_SANDBOX }}:5432/${{ secrets.DB_DBNAME }} \
                   -user=${{ secrets.DB_USERNAME }} \
                   -password=${{ secrets.DB_PASSWORD }} \
                   -locations=filesystem:app/src/main/resources/db/migration \
                   validate;
          fi
